#!/bin/bash
#
# sync-ai-instructions.sh
# ========================
# Syncs AI.md (source of truth) to all tool-specific instruction files.
#
# Usage:
#   ./tooling/scripts/util/sync-ai-instructions.sh
#
# Files updated:
#   CLAUDE.md                              — Claude Code
#   .github/copilot-instructions.md        — GitHub Copilot
#   .cursorrules                           — Cursor
#   .windsurfrules                         — Windsurf / Codeium
#   CONVENTIONS.md                         — Aider and generic tools

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "${PROJECT_DIR}"

SOURCE="AI.md"

if [[ ! -f "${SOURCE}" ]]; then
    echo "ERROR: ${SOURCE} not found. Run from project root or check the path."
    exit 1
fi

HEADER="$(cat <<'EOF'
# ⚠️  DO NOT EDIT THIS FILE DIRECTLY
# This file is auto-synced from AI.md
# To update: edit AI.md, then run tooling/scripts/util/sync-ai-instructions.sh
#
EOF
)"

sync_file() {
    local target="$1"
    local dir
    dir="$(dirname "${target}")"
    mkdir -p "${dir}"
    { echo "${HEADER}"; cat "${SOURCE}"; } > "${target}"
    echo "  ✓ ${target}"
}

echo "Syncing AI.md to tool-specific instruction files..."
echo ""

sync_file "CLAUDE.md"
sync_file ".github/copilot-instructions.md"
sync_file ".cursorrules"
sync_file ".windsurfrules"
sync_file "CONVENTIONS.md"

echo ""
echo "Done. All instruction files are up to date."
